const strings = {
  app_name: 'Dindin na Linha',
  main_title: 'Despesas',
  add_disbursement: 'Adicionar desembolso',
  expense_name: 'Nome da despesa:',
  expense_name_placeholder: 'Ex: CDB, frutas, academia, etc',
  amount_disbursed: 'Valor desembolsado:',
  amount_disbursed_placeholder: 'R$ 00,00',
  button_add: 'Adicionar',
  add_new_cost: 'Adicionar novo gasto',
  add_category: 'Adicionar categoria',
  category_name: 'Nome da categoria:',
  category_name_placeholder: 'Ex: Saúde, alimentação, educação, etc',
  hex_code: 'Código HEX (cor desejada):',
  hex_code_placeholder: '#000000',
  error: 'Erro',
  error_read_data: 'Erro ao ler os dados',
  error_delete_all: 'Erro ao deletar todos os dados',
  error_add_category: 'Erro ao adicionar categoria',
  error_add_disbursement: 'Erro ao adicionar desembolso',
  error_delete_category: 'Erro ao deletar categoria',
  error_delete_disbursement: 'Erro ao deletar desembolso',
  error_update_category: 'Erro ao atualizar categoria',
  error_update_disbursement: 'Erro ao atualizar desembolso',
  error_delete_all_categories: 'Erro ao deletar todas as categorias',
  error_delete_all_disbursements: 'Erro ao deletar todos os desembolsos',
  error_delete_all_data: 'Erro ao deletar todos os dados',
  success: 'Sucesso',
  success_delete_all: 'Todos os dados foram deletados',
  success_add_category: 'Categoria adicionada com sucesso',
  success_add_disbursement: 'Desembolso adicionado com sucesso',
  success_delete_category: 'Categoria deletada com sucesso',
  success_delete_disbursement: 'Desembolso deletado com sucesso',
  success_update_category: 'Categoria atualizada com sucesso',
  success_update_disbursement: 'Desembolso atualizado com sucesso',
  success_delete_all_categories: 'Todas as categorias foram deletadas',
  success_delete_all_disbursements: 'Todos os desembolsos foram deletados',
  success_delete_all_data: 'Todos os dados foram deletados',
  confirm_delete_all: 'Deseja realmente deletar todos os dados?',
  confirm_delete_category: 'Deseja realmente deletar a categoria?',
  confirm_delete_disbursement: 'Deseja realmente deletar o desembolso?',
  confirm_delete_all_categories: 'Deseja realmente deletar todas as categorias?',
  confirm_delete_all_disbursements: 'Deseja realmente deletar todos os desembolsos?',
  confirm_delete_all_data: 'Deseja realmente deletar todos os dados?',
  cancel: 'Cancelar',
  delete: 'Deletar',
  delete_all: 'Deletar tudo',
  delete_category: 'Deletar categoria',
  delete_disbursement: 'Deletar desembolso',
  delete_all_categories: 'Deletar todas as categorias',
  delete_all_disbursements: 'Deletar todos os desembolsos',
  delete_all_data: 'Deletar todos os dados',
  update: 'Atualizar',
  update_category: 'Atualizar categoria',
  update_disbursement: 'Atualizar desembolso',
  update_all_categories: 'Atualizar todas as categorias',
  update_all_disbursements: 'Atualizar todos os desembolsos',
  update_all_data: 'Atualizar todos os dados',
  no_data_to_display: 'Nenhum dado para exibir',
  no_categories_to_display: 'Nenhuma categoria para exibir',
  no_disbursements_to_display: 'Nenhum desembolso para exibir',
  not_found: 'Item não encontrado',
};

export default strings;
